"""
response_behavior.py
--------------------
Human-like response behaviour engine for EVA.

Responsibilities
----------------
1. Decide whether EVA should reply or stay silent (should_reply).
   - True for greetings, questions, requests, statements, and conversations.
   - False for empty input, punctuation-only, gibberish/keysmash, or silence tokens.
2. Calculate natural initial typing delay:
   - Very short replies: 0.0 - 0.4s
   - Normal replies: 0.4 - 1.2s
   - Longer/complex replies: 1.0 - 1.8s
3. Split response into natural conversational chunks:
   - Short response: 1 chunk
   - Medium response: 2 chunks
   - Long response: up to 3 chunks
4. Calculate dynamic delay between chunks (0.4s - 0.9s).
"""

from __future__ import annotations

import logging
import random
import re
from typing import TypedDict

logger = logging.getLogger(__name__)


# ─── Configuration Limits ──────────────────────────────────────────────────────

# Initial delay limits (seconds)
INITIAL_DELAY_MIN: float = 0.0
INITIAL_DELAY_MAX: float = 1.8

# Inter-chunk delay limits (seconds)
CHUNK_DELAY_MIN: float = 0.4
CHUNK_DELAY_MAX: float = 0.9

# Maximum chunks EVA will ever emit in a single turn
MAX_CHUNKS: int = 3

# Length thresholds for chunking and delay
SHORT_REPLY_CHARS: int = 60
MEDIUM_REPLY_CHARS: int = 160
LONG_REPLY_CHARS: int = 300


# ─── Return Type ───────────────────────────────────────────────────────────────

class ResponseBehavior(TypedDict):
    should_reply:  bool        # Whether EVA should reply (True) or stay silent (False)
    initial_delay: float       # Seconds to wait before the first chunk
    chunks:        list[str]   # 1-3 conversational chunks
    chunk_delay:   float       # Seconds between consecutive chunks


# ─── Public API ────────────────────────────────────────────────────────────────

def build_response_behavior(
    user_message: str,
    ai_response: str,
) -> ResponseBehavior:
    """
    Build the full response behaviour plan for an interaction.

    Parameters
    ----------
    user_message:
        The raw text received from the user.
    ai_response:
        The text generated by EVA's conversation model.

    Returns
    -------
    ResponseBehavior
        A typed dictionary with should_reply, initial_delay, chunks, chunk_delay.
    """
    # 1. Decide whether EVA should reply
    reply = should_respond(user_message)

    if not reply:
        logger.info(
            "response_behavior: EVA decided to stay silent for input %r",
            user_message[:50],
        )
        return ResponseBehavior(
            should_reply=False,
            initial_delay=0.0,
            chunks=[],
            chunk_delay=0.0,
        )

    text = (ai_response or "").strip()
    if not text:
        return ResponseBehavior(
            should_reply=False,
            initial_delay=0.0,
            chunks=[],
            chunk_delay=0.0,
        )

    # 2. Split response into natural chunks (1 to 3)
    chunks = split_into_chunks(text)

    # 3. Calculate initial typing delay
    initial_delay = calculate_initial_delay(text)

    # 4. Calculate inter-chunk delay
    chunk_delay = calculate_inter_chunk_delay() if len(chunks) > 1 else 0.0

    logger.info(
        "response_behavior: reply=True | chunks=%d | "
        "initial_delay=%.2fs | chunk_delay=%.2fs",
        len(chunks),
        initial_delay,
        chunk_delay,
    )

    return ResponseBehavior(
        should_reply=True,
        initial_delay=initial_delay,
        chunks=chunks,
        chunk_delay=chunk_delay,
    )


# ─── 1. Reply Decision ────────────────────────────────────────────────────────

def should_respond(user_message: str) -> bool:
    """
    Evaluate whether EVA should reply or stay silent.

    Returns True for:
    - Greetings, questions, requests, emotional statements, conversations.

    Returns False for:
    - Empty or whitespace-only messages.
    - Pure punctuation / symbol spam (e.g. '...', '???', '---', '!??').
    - Meaningless gibberish / keysmash (e.g. 'asdfghjkl', 'qwertyuiop', 'zzzzz').
    - Dead-end single silence/sleeping tokens (e.g. 'shh', 'shhh', 'zzzz', 'k.').
    - Single non-word characters (e.g. 'x', 'q', 'j').
    """
    if not user_message:
        return False

    text = user_message.strip()
    if not text:
        return False

    # 1. Pure punctuation or symbols without any alphanumeric words
    alphanumeric = re.findall(r"[\w\u0900-\u097F]", text, flags=re.UNICODE)
    if not alphanumeric:
        return False

    # 2. Known silence / sleep / dead-end tokens
    lower = text.lower().strip(".!?, -")
    silence_tokens = {
        "shh", "shhh", "shush", "zzz", "zzzz", "zzzzz",
        "k.", "...", "silence", "(silence)", "afk", "brb",
    }
    if lower in silence_tokens:
        return False

    # 3. Single non-word character (e.g. 'x', 'q', 'z', '1')
    # Exceptions: 'a', 'i' in English, 'o' in Roman Urdu
    if len(lower) == 1 and lower not in {"a", "i", "o", "u"}:
        return False

    # 4. Keysmash / Repeated character detection (e.g. 'aaaaaaa', '1111111')
    if len(lower) >= 4 and len(set(lower)) == 1:
        return False

    # 5. Common keyboard row keysmash check
    keysmashes = {
        "asdf", "asdfg", "asdfgh", "asdfghj", "asdfghjkl",
        "qwerty", "qwertyuiop", "zxcvbnm", "hjkl", "dfgh",
        "ghjkl", "sdfgh", "cvbnm", "werty", "ertyu",
    }
    if lower in keysmashes:
        return False

    # 6. Repetitive consonant-only mash of length >= 6 (no vowels a, e, i, o, u, y)
    if len(lower) >= 6 and not any(v in lower for v in "aeiouy\u0900-\u097F"):
        return False

    # All genuine conversational messages get a reply
    return True


# ─── 2. Initial Delay ─────────────────────────────────────────────────────────

def calculate_initial_delay(response_text: str) -> float:
    """
    Calculate realistic delay before EVA starts sending the response.

    - Very short/simple replies (< 60 chars): 0.0 - 0.4s
    - Normal replies (60 - 160 chars): 0.4 - 1.2s
    - Longer/complex replies (> 160 chars): 1.0 - 1.8s
    """
    text = (response_text or "").strip()
    length = len(text)

    if length <= SHORT_REPLY_CHARS:
        # 0.0s to 0.35s for quick snappy answers
        delay = random.uniform(0.0, 0.35)
    elif length <= MEDIUM_REPLY_CHARS:
        # Scales smoothly between 0.4s and 1.1s
        scale = (length - SHORT_REPLY_CHARS) / (MEDIUM_REPLY_CHARS - SHORT_REPLY_CHARS)
        base = 0.4 + scale * 0.6
        delay = base + random.uniform(-0.1, 0.1)
    else:
        # Scales between 1.0s and 1.8s
        scale = min((length - MEDIUM_REPLY_CHARS) / (LONG_REPLY_CHARS - MEDIUM_REPLY_CHARS), 1.0)
        base = 1.0 + scale * 0.7
        delay = base + random.uniform(-0.1, 0.1)

    return round(max(INITIAL_DELAY_MIN, min(INITIAL_DELAY_MAX, delay)), 2)


# ─── 3. Chunk Count & Sentence Splitting ──────────────────────────────────────

def split_into_chunks(response_text: str) -> list[str]:
    """
    Split *response_text* into 1 to 3 natural conversational chunks.

    Rules
    -----
    - Short casual reply (<= 140 chars or 1 sentence): 1 chunk.
    - Topic explanations / multi-sentence replies (> 140 chars with 2+ sentences): 2 chunks.
    - Long detailed explanations (> 260 chars with 4+ sentences): 3 chunks.
    - Splitting happens strictly at natural sentence/conversational boundaries.
    """
    text = (response_text or "").strip()
    if not text:
        return [""]

    if len(text) <= 140:
        return [text]

    sentences = _tokenise_sentences(text)

    if len(sentences) <= 1:
        return [text]

    target = _decide_chunk_count(len(sentences), len(text))
    if target <= 1:
        return [text]

    return _group_sentences(sentences, target)


def _tokenise_sentences(text: str) -> list[str]:
    """
    Tokenise text into individual sentences using punctuation boundaries.
    Supports English, Hindi (।), Urdu, Roman Urdu, semicolons (;), and newlines.
    """
    pattern = r"(?<=[.!?…।;\n])\s+"
    parts = re.split(pattern, text)
    return [s.strip() for s in parts if s.strip()]


def _decide_chunk_count(sentence_count: int, text_length: int) -> int:
    """
    Decide chunk count:
    - 1 chunk for short replies (<= 140 chars or 1 sentence)
    - 2 chunks for topic explanations (2-3 sentences and > 140 chars)
    - 3 chunks for long detailed explanations (4+ sentences and > 260 chars)
    """
    if sentence_count <= 1 or text_length <= 140:
        return 1
    elif sentence_count <= 3 or text_length <= 260:
        return 2
    else:
        return MAX_CHUNKS


def _group_sentences(sentences: list[str], n: int) -> list[str]:
    """
    Evenly distribute sentences into *n* chunk groups.
    The last chunk absorbs any remainder so no content is lost.
    """
    if n >= len(sentences):
        return sentences

    per = len(sentences) // n
    result: list[str] = []

    for i in range(n):
        start = i * per
        end = start + per if i < n - 1 else len(sentences)
        part = " ".join(sentences[start:end]).strip()
        if part:
            result.append(part)

    return result if result else [" ".join(sentences)]


# ─── 4. Inter-Chunk Delay ─────────────────────────────────────────────────────

def calculate_inter_chunk_delay() -> float:
    """
    Calculate natural conversational pause between chunks.
    Varies dynamically between CHUNK_DELAY_MIN (0.4s) and CHUNK_DELAY_MAX (0.9s).
    """
    return round(random.uniform(CHUNK_DELAY_MIN, CHUNK_DELAY_MAX), 2)
